#! /bin/bash

echo "Creating directories"
cd "$HOME" 
mkdir www
mkdir git

echo "Installing asdf"
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1

echo "Installing zsh stuff"
cd "$HOME/git"
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git 

echo "Installing apt packages"
# Vscode
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

# Vivaldi
sudo sh -c 'echo "deb http://repo.vivaldi.com/stable/deb/ stable main" >> /etc/apt/sources.list'
wget -q -O - http://repo.vivaldi.com/stable/linux_signing_key.pub | sudo apt-key add -

sudo apt update
sudo apt install software-properties-common apt-transport-https zsh code vivaldi-stable zsh-syntax-highlighting

echo "Installing flatpak apps"
flatpak install flathub md.obsidian.Obsidian -y
flatpak install flathub com.spotify.Client -y 
flatpak install flathub com.discordapp.Discord -y

echo "Installing fonts"
fc-cache -vf

chsh -s $(which zsh)
echo "Please, logout to use zsh as default shell"
